apiVersion: v1
kind: Service
metadata:
  name: hotstar-service
  labels:
    app: hotstar-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: hotstar-deployment
